name: Bug report
description: Create a bug report to help us improve
labels: [bug, needs triage]
body:
  - type: checkboxes
    id: checks
    attributes:
      label: "Checks"
      options:
        - label: "I am able to reproduce the bug with the [latest version](https://github.com/MDP43140/LTECleanerFOSS/releases/latest)."
          required: true
        - label: "I made sure that there are *no existing issues* - [open](https://github.com/MDP43140/LTECleanerFOSS/issues) or [closed](https://github.com/MDP43140/LTECleanerFOSS/issues?q=is%3Aissue+is%3Aclosed) - which I could contribute my information to."
          required: true
        - label: "I have read the [Wiki](https://github.com/MDP43140/LTECleanerFOSS/wiki) and my problem isn't listed."
          required: true
        - label: "I have taken the time to fill in all the required details. I understand that the bug report will be dismissed otherwise."
          required: true

  - type: input
    id: app-version
    attributes:
      label: Affected version
      description: In which version did you encounter the bug?
      placeholder: "x.x.x"
    validations:
      required: true

  - type: textarea
    id: reproduce-steps
    attributes:
      label: Steps to reproduce the bug
      description: |
        What did you do for the bug to show up?

        If you can't cause the bug to show up again reliably (and hence don't have a proper set of steps to give us), please still try to give as many details as possible on how you think you encountered the bug.
      placeholder: |
        1. Go to '...'
        2. Scroll down to '....'
        3. Click on '....'
    validations:
      required: true

  - type: textarea
    id: expected-and-actual-behavior
    attributes:
      label: Expected & Actual behavior
      description: What do you expect to happen? and What actually happens with the steps given above?
      placeholder: "I expect it to ..., but instead it ..."

  - type: textarea
    id: screen-media
    attributes:
      label: Screenshots/Screen recordings
      description: |
        A picture or video is worth a thousand words.

        If applicable, add screenshots or a screen recording to help explain your problem.
        GitHub supports uploading them directly in the text box.
        If your file is too big for GitHub to accept, try to compress it (ZIP-file) or feel free to paste a link to an image/video hoster here instead.

        :heavy_exclamation_mark: DON'T POST SCREENSHOTS OF THE ERROR PAGE.
        Instead, follow the instructions in the "Logs" section below.

  - type: textarea
    id: logs
    attributes:
      label: Logs
      description: If your bug includes a crash (where you're shown the Error Report page with a bunch of info), tap on "Share formatted log" at the bottom, click "Copy to clipboard", and paste it here.
      placeholder: |
        Exception
        App language: en
        App version: ...
        Device: brand MO-DEL
        OS Version: Linux brand/model/model:34/build/build:author/key 14 - 34
        GMT Time: 2024/../.. ..:..
        Crash log:
        java.lang.Exception: ...
        	at ...(...:...)
        	...

  - type: input
    id: device-os
    attributes:
      label: Affected Android/Custom ROM version
      description: With what Operating System (+ version) did you encounter the bug?
      placeholder: "eg. Android 14/LineageOS 21"

  - type: input
    id: device-model
    attributes:
      label: Affected device model
      description: On what device did you encounter the bug?
      placeholder: "eg. Google Pixel 7/Samsung Galaxy S10"

  - type: textarea
    id: additional-info
    attributes:
      label: Additional information
      description: Any other information you'd like to include
