name: Feature request
description: Suggest an idea for this project
labels: [enhancement]
body:
  - type: checkboxes
    id: checklist
    attributes:
      label: "Checklist"
      options:
        - label: "I made sure that there are *no existing issues* - [open](https://github.com/MDP43140/LTECleanerFOSS/issues) or [closed](https://github.com/MDP43140/LTECleanerFOSS/issues?q=is%3Aissue+is%3Aclosed)."
          required: true
        - label: "I have taken the time to fill in all the required details. I understand that the feature request will be dismissed otherwise."
          required: true
        - label: "This issue contains only one feature request."
          required: true

  - type: textarea
    id: describe
    attributes:
      label: "Is your feature request related to a problem? Please describe."
      description: A clear and concise description of what the problem is.
      placeholder: "eg. I'm always frustrated when ..."

  - type: textarea
    id: solution
    attributes:
      label: "Describe the solution you'd like"
      description: A clear and concise description of what you want to happen.
      placeholder: "eg. I want it to ..."

  - type: textarea
    id: additional_info
    attributes:
      label: "Additional context"
      description: Add any other context or screenshots about the feature request here.
      placeholder: "eg. I saw App B has ... feature, it has ... and ..., just look at the screenshot that i sent"
