/*
 * SPDX-FileCopyrightText: 2020-2023 Hunter J Drum
 * SPDX-FileCopyrightText: 2024-2025 MDP43140
 * SPDX-License-Identifier: GPL-3.0-or-later
 */
package theredspy15.ltecleanerfoss
object Constants {
	const val BGCLEAN_WORK_NAME = "scheduled_cleanup_work"
	const val BGCLEAN_WORK_TAG = "cleanup_work_tag"
	const val NOTIFICATION_ID_SERVICE = 1
	const val NOTIFICATION_CHANNEL_SERVICE = "CLEANUP_SERVICE"
	val blacklistDefault: Set<String> = setOf(
		".*\\.log$",
		".*\\.tmp$",
		".*/log",
		".*/Logs",
		".*/logs",
		"/storage/emulated/0/.*albumthumbs\\?",
		"/storage/emulated/0/Android/data/.*/fastbot", // Seemingly generated by apps that uses some kind of Bytedance components? (or perhaps TikTok analytics or Pangle?)
		"/storage/emulated/0/Android/data/.*/files/tombstone_.*",
		"/storage/emulated/0/Android/data/.*/files/al",
		"/storage/emulated/0/Android/data/.*/files/il2cpp", // generated by Unity games, i hope this wont slow down loading
		"/storage/emulated/0/Android/data/.*/files/supersonicads",
		"/storage/emulated/0/Android/data/.*/files/Unity/.*/Analytics",
		"/storage/emulated/0/Android/data/.*/files/UnityServicesCachedMetrics",
		"/storage/emulated/0/Android/data/.*/files/.*\\.pangled",
		"/storage/emulated/0/Android/data/.*/files/\\..*\\.vguard", // generated by apps that uses V-Key (root detection system)
		"/storage/emulated/0/Android/data/.*/files/.*mobvista",
		"/storage/emulated/0/Android/data/.*/files/.*splashad",
		"/storage/emulated/0/Android/data/.*/files/.*UnityAdsVideoCache",
		"/storage/emulated/0/Android/data/com\\.facebook\\.katana/files/fb_temp",
		"/storage/emulated/0/Android/data/com\\.facebook\\.katana/files/secure_shared",
		"/storage/emulated/0/Android/data/com\\.ss\\.android\\.ugc\\.trill/files/monitor_data_switch",
		"/storage/emulated/0/Android/\\..*\\.vguard", // generated by apps that uses V-Key (root detection system)
		"/storage/emulated/0/ApkEditor/tmp",
		"/storage/emulated/0/ColorOS",
		"/storage/emulated/0/com\\.UCMobile\\.intl", // ulog/.*\\.ulog // generated by UC Browser
		"/storage/emulated/0/DCIM/Camera/\\.escheck\\.tmp", // generated by ES File Explorer (for anyone that still using it, please stop using it)
		"/storage/emulated/0/DCIM/Camera/thumbnails", // seen on LineageOS, or probably generated by other app, idk
		"/storage/emulated/0/Download/AppMonitorSDKLogs", // can be seen on ColorOS
		"/storage/emulated/0/Download/MGC_CRASH_LOG", // generated by Google Camera app
		"/storage/emulated/0/Download/UCDownloads", // generated by UC Browser
		"/storage/emulated/0/MIUI/debug_log", // powerinfo/result_reason
		"/storage/emulated/0/MIUI/BugReportCache",
		"/storage/emulated/0/supercache",
		"/storage/emulated/0/Tencent", // XG/Logs/YYYYMMDD/N\.1\.app\.log // apparently was used for freefire push notification svc logs??
		"/storage/emulated/0/UCShare", // .ucThumb/videoThumb_-... // generated by UC Browser
		"/storage/emulated/0/UnityAdsVideoCache",
		"/storage/emulated/0/\\.chartboost", // most modern apps that displays ads (even Chartboost) should never put ads folder in sdcard anymore, but just in case
		"/storage/emulated/0/\\.DataStorage", // ContextData\\.xml // generated by UC Browser (but also ES File Explorer?)
		"/storage/emulated/0/\\.dev", // can be seen on ColorOS
		"/storage/emulated/0/\\.estrongs", // generated by ES File Explorer
		"/storage/emulated/0/\\.ext4", // can be seen on ColorOS
		"/storage/emulated/0/\\.sstmp", // can be seen on ColorOS
		"/storage/emulated/0/\\.userReturn", // es file explorer stuff?
		"/storage/emulated/0/\\.Uc2DataStorage", // Uc2ContextData.xml // generated by UC Browser
		"/storage/emulated/0/\\.UTSystemConfig",  // Global/Alvin2.xml // generated by UC Browser
		"/storage/emulated/0/\\.Uc2UTSystemConfig", //  Global/Uc2Alvin2.xml // generated by UC Browser
		"/storage/emulated/0/crash\\.txt$", // Usually generated by GameGuardian
		"/storage/emulated/0/logcat\\.txt$", // Usually generated by GameGuardian
		"/storage/emulated/0/gltools_crashlog\\.txt$", // generated by GLTools
		"/storage/emulated/0/.*Analytics",
		"/storage/emulated/0/.*Cache",
		"/storage/emulated/0/.*cache",
		"/storage/emulated/0/.*/\\.DS_Store$",
		"/storage/emulated/0/.*/\\.nomedia$",
		"/storage/emulated/0/.*/\\.spotlight-V100",
		"/storage/emulated/0/.*/\\.Trash",
		"/storage/emulated/0/.*\\.exo$",
		"/storage/emulated/0/.*\\.thumb[0-9]",
		"/storage/emulated/0/.*\\.thumbnails\\?$",
		"/storage/emulated/0/.*thumbs?\\.db",
		"/storage/emulated/0/.*/bugreports",
		"/storage/emulated/0/.*/Bugreport",
		"/storage/emulated/0/.*/desktop\\.ini$",
		"/storage/emulated/0/.*/fseventd",
		"/storage/emulated/0/.*/leakcanary",
		"/storage/emulated/0/.*/LOST\\.DIR$"
	)
	val blacklistOnDefault: Set<String> = setOf(
		".*\\.log$",
		".*\\.tmp$",
		".*/log",
		".*/Logs",
		".*/logs",
		//"/storage/emulated/0/.*albumthumbs\\?",
		"/storage/emulated/0/Android/data/.*/fastbot", // Seemingly generated by apps that uses some kind of Bytedance components? (or perhaps TikTok analytics or Pangle?)
		"/storage/emulated/0/Android/data/.*/files/tombstone_.*",
		//"/storage/emulated/0/Android/data/.*/files/al",
		"/storage/emulated/0/Android/data/.*/files/il2cpp", // generated by Unity games, i hope this wont slow down loading
		"/storage/emulated/0/Android/data/.*/files/supersonicads",
		"/storage/emulated/0/Android/data/.*/files/Unity/.*/Analytics",
		"/storage/emulated/0/Android/data/.*/files/UnityServicesCachedMetrics",
		"/storage/emulated/0/Android/data/.*/files/.*\\.pangled",
		"/storage/emulated/0/Android/data/.*/files/\\..*\\.vguard", // generated by apps that uses V-Key (root detection system)
		"/storage/emulated/0/Android/data/.*/files/.*mobvista",
		"/storage/emulated/0/Android/data/.*/files/.*splashad",
		"/storage/emulated/0/Android/data/.*/files/.*UnityAdsVideoCache",
		"/storage/emulated/0/Android/data/com\\.facebook\\.katana/files/fb_temp",
		"/storage/emulated/0/Android/data/com\\.facebook\\.katana/files/secure_shared",
		"/storage/emulated/0/Android/data/com\\.ss\\.android\\.ugc\\.trill/files/monitor_data_switch",
		"/storage/emulated/0/Android/\\..*\\.vguard", // generated by apps that uses V-Key (root detection system)
		"/storage/emulated/0/ApkEditor/tmp",
		"/storage/emulated/0/ColorOS",
		"/storage/emulated/0/com\\.UCMobile\\.intl", // ulog/.*\\.ulog // generated by UC Browser
		"/storage/emulated/0/DCIM/Camera/\\.escheck\\.tmp", // generated by ES File Explorer (for anyone that still using it, please stop using it)
		"/storage/emulated/0/DCIM/Camera/thumbnails", // seen on LineageOS, or probably generated by other app, idk
		"/storage/emulated/0/Download/AppMonitorSDKLogs", // can be seen on ColorOS
		"/storage/emulated/0/Download/MGC_CRASH_LOG", // generated by Google Camera app?
		"/storage/emulated/0/Download/UCDownloads", // generated by UC Browser
		"/storage/emulated/0/MIUI/debug_log", // powerinfo/result_reason
		"/storage/emulated/0/MIUI/BugReportCache",
		//"/storage/emulated/0/supercache",
		//"/storage/emulated/0/Tencent", // XG/Logs/YYYYMMDD/N\.1\.app\.log // apparently was used for freefire push notification svc logs??
		"/storage/emulated/0/UCShare", // .ucThumb/videoThumb_-... // generated by UC Browser
		//"/storage/emulated/0/UnityAdsVideoCache",
		//"/storage/emulated/0/\\.chartboost", // most modern apps that displays ads (even Chartboost) should never put ads folder in sdcard anymore, but just in case
		"/storage/emulated/0/\\.DataStorage", // ContextData\\.xml // generated by UC Browser (but also ES File Explorer?)
		"/storage/emulated/0/\\.dev", // can be seen on ColorOS
		//"/storage/emulated/0/\\.estrongs", // generated by ES File Explorer
		"/storage/emulated/0/\\.ext4", // can be seen on ColorOS
		"/storage/emulated/0/\\.sstmp", // can be seen on ColorOS
		//"/storage/emulated/0/\\.userReturn", // es file explorer stuff?
		"/storage/emulated/0/\\.Uc2DataStorage", // Uc2ContextData.xml // generated by UC Browser
		"/storage/emulated/0/\\.UTSystemConfig",  // Global/Alvin2.xml // generated by UC Browser
		"/storage/emulated/0/\\.Uc2UTSystemConfig", //  Global/Uc2Alvin2.xml // generated by UC Browser
		//"/storage/emulated/0/crash\\.txt$", // Usually generated by GameGuardian
		//"/storage/emulated/0/logcat\\.txt$", // Usually generated by GameGuardian
		"/storage/emulated/0/gltools_crashlog\\.txt$", // generated by GLTools
		"/storage/emulated/0/.*Analytics",
		"/storage/emulated/0/.*Cache",
		"/storage/emulated/0/.*cache",
		//"/storage/emulated/0/.*/\\.DS_Store$",
		"/storage/emulated/0/.*/\\.nomedia$",
		//"/storage/emulated/0/.*/\\.spotlight-V100",
		//"/storage/emulated/0/.*/\\.Trash",
		//"/storage/emulated/0/.*\\.exo$",
		//"/storage/emulated/0/.*\\.thumb[0-9]",
		//"/storage/emulated/0/.*\\.thumbnails\\?$",
		//"/storage/emulated/0/.*thumbs?\\.db",
		//"/storage/emulated/0/.*/bugreports",
		//"/storage/emulated/0/.*/Bugreport",
		//"/storage/emulated/0/.*/desktop\\.ini$",
		//"/storage/emulated/0/.*/fseventd",
		//"/storage/emulated/0/.*/leakcanary",
		//"/storage/emulated/0/.*/LOST\\.DIR$"
	)
	val whitelistDefault: Set<String> = emptySet()
	val whitelistOnDefault: Set<String> = emptySet()
	val filter_apkFiles: ArrayList<String> = arrayListOf(
		".aab", // should this be considered?
		".apk",
		".apks",
		".apkm"
	)
	val filter_genericFiles: ArrayList<String> = arrayListOf(
		".tmp",
		".log"
	)
	val filter_genericFolders: ArrayList<String> = arrayListOf(
		"Logs",
		"logs",
		"temp",
		"Temporary",
		"temporary"
	)
	val filter_autoWhite: ArrayList<String> = arrayListOf(
		"backup",
		"copy",
		"copies",
		"important",
		"do_not_edit",
		".stfolder"
	)
}