-optimizationpasses 9
-optimizations !code/simplification/arithmetic,!field/*,!class/merging/*
-allowaccessmodification
-keepattributes SourceFile,LineNumberTable
-dontobfuscate
-renamesourcefileattribute SourceFile